// <auto-generated />
using System;
using Gestion_SalleClasseEDT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gestion_SalleClasseEDT.Migrations
{
    [DbContext(typeof(EMITDbContext))]
    [Migration("20260613153320_AddMatiereFields")]
    partial class AddMatiereFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.AnneeAcademique", b =>
                {
                    b.Property<int>("IdAnnee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_annee");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnnee"));

                    b.Property<DateTime>("DateDebutAnnee")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut_annee");

                    b.Property<DateTime>("DateFinAnnee")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin_annee");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("libelle");

                    b.HasKey("IdAnnee");

                    b.ToTable("annee_academique", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClasse"));

                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer")
                        .HasColumnName("id_filiere");

                    b.Property<int>("IdSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    b.Property<string>("NomClasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_classe");

                    b.HasKey("IdClasse");

                    b.HasIndex("IdFiliere");

                    b.HasIndex("IdSemestre");

                    b.ToTable("classe", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Cours", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cours");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCours"));

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int>("IdProfesseur")
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur");

                    b.Property<int?>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<int>("IdSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeCours")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type_cours");

                    b.HasKey("IdCours");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdProfesseur");

                    b.HasIndex("IdSalle");

                    b.HasIndex("IdSemestre");

                    b.ToTable("cours", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Creneau", b =>
                {
                    b.Property<int>("IdCreneau")
                        .HasColumnType("integer")
                        .HasColumnName("id_creneau");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin");

                    b.Property<int>("IdCours")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours");

                    b.Property<string>("JourSemaine")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("jour_semaine");

                    b.Property<string>("SemaineType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("bpchar")
                        .HasColumnName("semaine_type");

                    b.HasKey("IdCreneau");

                    b.HasIndex("IdCours");

                    b.ToTable("creneau", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DemandeEdt", b =>
                {
                    b.Property<int>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_demande");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDemande"));

                    b.Property<DateTime?>("DateSouhaitee")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_souhaitee");

                    b.Property<TimeSpan?>("HeureDebutSouhaitee")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut_souhaitee");

                    b.Property<TimeSpan?>("HeureFinSouhaitee")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin_souhaitee");

                    b.Property<int?>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int?>("IdCours")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours");

                    b.Property<int>("IdDemandeur")
                        .HasColumnType("integer")
                        .HasColumnName("id_demandeur");

                    b.Property<int?>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int?>("IdNiveau")
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau");

                    b.Property<int?>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<int?>("IdValidateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_validateur");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeDemande")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("type_demande");

                    b.HasKey("IdDemande");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdCours");

                    b.HasIndex("IdDemandeur");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdNiveau");

                    b.HasIndex("IdSalle");

                    b.HasIndex("IdValidateur");

                    b.ToTable("demande_edt", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DisponibiliteProf", b =>
                {
                    b.Property<int>("IdDispo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_dispo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDispo"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin");

                    b.Property<int>("IdProfesseur")
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur");

                    b.Property<string>("JourSemaine")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("jour_semaine");

                    b.Property<string>("SemaineType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("bpchar")
                        .HasColumnName("semaine_type");

                    b.HasKey("IdDispo");

                    b.HasIndex("IdProfesseur");

                    b.ToTable("disponibilite_prof", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Filiere", b =>
                {
                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer")
                        .HasColumnName("id_filiere");

                    b.Property<string>("CodeFiliere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_filiere");

                    b.Property<int>("IdMention")
                        .HasColumnType("integer")
                        .HasColumnName("id_mention");

                    b.Property<string>("NomFiliere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_filiere");

                    b.HasKey("IdFiliere");

                    b.HasIndex("IdMention");

                    b.ToTable("filiere", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<string>("CodeMatiere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_matiere");

                    b.Property<int>("Credit")
                        .HasColumnType("integer")
                        .HasColumnName("credit");

                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer")
                        .HasColumnName("id_filiere");

                    b.Property<int?>("IdProfesseurResponsable")
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur_responsable");

                    b.Property<int>("IdRefSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_semestre");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_matiere");

                    b.Property<int>("VolumeHoraire")
                        .HasColumnType("integer")
                        .HasColumnName("volume_horaire");

                    b.HasKey("IdMatiere");

                    b.HasIndex("IdFiliere");

                    b.HasIndex("IdProfesseurResponsable");

                    b.HasIndex("IdRefSemestre");

                    b.ToTable("matiere", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Mention", b =>
                {
                    b.Property<int>("IdMention")
                        .HasColumnType("integer")
                        .HasColumnName("id_mention");

                    b.Property<string>("CodeMention")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_mention");

                    b.Property<string>("NomMention")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_mention");

                    b.HasKey("IdMention");

                    b.HasIndex("CodeMention")
                        .IsUnique();

                    b.ToTable("mention", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNiveau"));

                    b.Property<string>("CodeNiveau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code_niveau");

                    b.Property<int>("IdMention")
                        .HasColumnType("integer")
                        .HasColumnName("id_mention");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.HasKey("IdNiveau");

                    b.HasIndex("IdMention");

                    b.ToTable("niveau", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Professeur", b =>
                {
                    b.Property<int>("IdProfesseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProfesseur"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdProfesseur");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("professeur", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.PropositionAdmin", b =>
                {
                    b.Property<int>("IdProposition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_proposition");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProposition"));

                    b.Property<DateTime>("DateProposee")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_proposee");

                    b.Property<bool?>("EstAcceptee")
                        .HasColumnType("boolean")
                        .HasColumnName("est_acceptee");

                    b.Property<TimeSpan>("HeureDebutProposee")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut_proposee");

                    b.Property<TimeSpan>("HeureFinProposee")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin_proposee");

                    b.Property<int>("IdDemande")
                        .HasColumnType("integer")
                        .HasColumnName("id_demande");

                    b.Property<int>("IdSalleProposee")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle_proposee");

                    b.HasKey("IdProposition");

                    b.HasIndex("IdDemande");

                    b.HasIndex("IdSalleProposee");

                    b.ToTable("proposition_admin", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.RefSemestre", b =>
                {
                    b.Property<int>("IdRefSemestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_semestre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRefSemestre"));

                    b.Property<string>("CodeSemestre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code_semestre");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.HasKey("IdRefSemestre");

                    b.HasIndex("IdNiveau");

                    b.ToTable("ref_semestre", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<int>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("capacite");

                    b.Property<string>("CodeBatiment")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("bpchar")
                        .HasColumnName("code_batiment");

                    b.Property<int>("Etage")
                        .HasColumnType("integer")
                        .HasColumnName("etage");

                    b.Property<string>("NomSalle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_salle");

                    b.Property<string>("NumeroPorte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_porte");

                    b.Property<string>("TypeSalle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type_salle");

                    b.HasKey("IdSalle");

                    b.ToTable("salle", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Semestre", b =>
                {
                    b.Property<int>("IdSemestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSemestre"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<int>("IdAnnee")
                        .HasColumnType("integer")
                        .HasColumnName("id_annee");

                    b.Property<int>("IdRefSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_semestre");

                    b.HasKey("IdSemestre");

                    b.HasIndex("IdAnnee");

                    b.HasIndex("IdRefSemestre");

                    b.ToTable("semestre", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utilisateur", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Classe", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Filiere", "Filiere")
                        .WithMany("Classes")
                        .HasForeignKey("IdFiliere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Semestre", "Semestre")
                        .WithMany("Classes")
                        .HasForeignKey("IdSemestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Cours", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Classe", "Classe")
                        .WithMany("Cours")
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Matiere", "Matiere")
                        .WithMany("Cours")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Professeur", "Professeur")
                        .WithMany("Cours")
                        .HasForeignKey("IdProfesseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Salle", "Salle")
                        .WithMany("Cours")
                        .HasForeignKey("IdSalle");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Semestre", "Semestre")
                        .WithMany("Cours")
                        .HasForeignKey("IdSemestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Matiere");

                    b.Navigation("Professeur");

                    b.Navigation("Salle");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Creneau", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Cours", "Cours")
                        .WithMany("Creneaux")
                        .HasForeignKey("IdCours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DemandeEdt", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("IdClasse");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Cours", "Cours")
                        .WithMany("DemandesEdt")
                        .HasForeignKey("IdCours");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Utilisateur", "Demandeur")
                        .WithMany()
                        .HasForeignKey("IdDemandeur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("IdMatiere");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Niveau", "Niveau")
                        .WithMany()
                        .HasForeignKey("IdNiveau");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Salle", "Salle")
                        .WithMany("DemandesEdt")
                        .HasForeignKey("IdSalle");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Utilisateur", "Validateur")
                        .WithMany()
                        .HasForeignKey("IdValidateur");

                    b.Navigation("Classe");

                    b.Navigation("Cours");

                    b.Navigation("Demandeur");

                    b.Navigation("Matiere");

                    b.Navigation("Niveau");

                    b.Navigation("Salle");

                    b.Navigation("Validateur");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DisponibiliteProf", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Professeur", "Professeur")
                        .WithMany("Disponibilites")
                        .HasForeignKey("IdProfesseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Filiere", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Mention", "Mention")
                        .WithMany("Filieres")
                        .HasForeignKey("IdMention")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mention");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Matiere", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Filiere", "Filiere")
                        .WithMany("Matieres")
                        .HasForeignKey("IdFiliere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Professeur", "ProfesseurResponsable")
                        .WithMany()
                        .HasForeignKey("IdProfesseurResponsable");

                    b.HasOne("Gestion_SalleClasseEDT.Models.RefSemestre", "RefSemestre")
                        .WithMany("Matieres")
                        .HasForeignKey("IdRefSemestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");

                    b.Navigation("ProfesseurResponsable");

                    b.Navigation("RefSemestre");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Niveau", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Mention", "Mention")
                        .WithMany("Niveaux")
                        .HasForeignKey("IdMention")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mention");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.PropositionAdmin", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.DemandeEdt", "Demande")
                        .WithMany("Propositions")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("IdSalleProposee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.RefSemestre", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Niveau", "Niveau")
                        .WithMany("RefSemestres")
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Semestre", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.AnneeAcademique", "AnneeAcademique")
                        .WithMany("Semestres")
                        .HasForeignKey("IdAnnee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.RefSemestre", "RefSemestre")
                        .WithMany("Semestres")
                        .HasForeignKey("IdRefSemestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeAcademique");

                    b.Navigation("RefSemestre");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.AnneeAcademique", b =>
                {
                    b.Navigation("Semestres");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Classe", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Cours", b =>
                {
                    b.Navigation("Creneaux");

                    b.Navigation("DemandesEdt");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DemandeEdt", b =>
                {
                    b.Navigation("Propositions");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Filiere", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Matieres");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Matiere", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Mention", b =>
                {
                    b.Navigation("Filieres");

                    b.Navigation("Niveaux");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Niveau", b =>
                {
                    b.Navigation("RefSemestres");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Professeur", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Disponibilites");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.RefSemestre", b =>
                {
                    b.Navigation("Matieres");

                    b.Navigation("Semestres");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Salle", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("DemandesEdt");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Semestre", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Cours");
                });
#pragma warning restore 612, 618
        }
    }
}
