// <auto-generated />
using System;
using Gestion_SalleClasseEDT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gestion_SalleClasseEDT.Migrations
{
    [DbContext(typeof(EMITDbContext))]
    [Migration("20260711214110_AddReglageDisponibilite")]
    partial class AddReglageDisponibilite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.AffectationMatiere", b =>
                {
                    b.Property<int>("IdAffectation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_affectation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAffectation"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean")
                        .HasColumnName("est_actif");

                    b.Property<int>("HeuresCm")
                        .HasColumnType("integer")
                        .HasColumnName("heures_cm");

                    b.Property<int>("HeuresTd")
                        .HasColumnType("integer")
                        .HasColumnName("heures_td");

                    b.Property<int>("HeuresTp")
                        .HasColumnType("integer")
                        .HasColumnName("heures_tp");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int>("IdProfesseur")
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur");

                    b.Property<int>("IdSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    b.Property<int>("VolumeHoraireTotal")
                        .HasColumnType("integer")
                        .HasColumnName("volume_horaire_total");

                    b.HasKey("IdAffectation");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdProfesseur");

                    b.HasIndex("IdSemestre");

                    b.ToTable("affectation_matiere", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.AnneeAcademique", b =>
                {
                    b.Property<int>("IdAnnee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_annee");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnnee"));

                    b.Property<DateTime?>("DateArchivage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_archivage");

                    b.Property<DateTime>("DateDebutAnnee")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut_annee");

                    b.Property<DateTime>("DateFinAnnee")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin_annee");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean")
                        .HasColumnName("est_active");

                    b.Property<bool>("EstArchivee")
                        .HasColumnType("boolean")
                        .HasColumnName("est_archivee");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("libelle");

                    b.HasKey("IdAnnee");

                    b.ToTable("annee_academique", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_audit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClasse"));

                    b.Property<string>("CodeClasse")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_classe");

                    b.Property<int>("Effectif")
                        .HasColumnType("integer")
                        .HasColumnName("effectif");

                    b.Property<bool>("EstArchivee")
                        .HasColumnType("boolean")
                        .HasColumnName("est_archivee");

                    b.Property<int>("IdAnneeAcademique")
                        .HasColumnType("integer")
                        .HasColumnName("id_annee_academique");

                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer")
                        .HasColumnName("id_filiere");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau");

                    b.Property<string>("NomClasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_classe");

                    b.HasKey("IdClasse");

                    b.HasIndex("IdAnneeAcademique");

                    b.HasIndex("IdFiliere");

                    b.HasIndex("IdNiveau");

                    b.ToTable("classe", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Cours", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cours");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCours"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Evaluation")
                        .HasColumnType("text")
                        .HasColumnName("evaluation");

                    b.Property<int?>("IdAffectation")
                        .HasColumnType("integer")
                        .HasColumnName("id_affectation");

                    b.Property<int?>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int?>("IdGroupe")
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int?>("IdProfesseur")
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur");

                    b.Property<int?>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<int>("IdSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("teaching_mode");

                    b.Property<string>("Objectives")
                        .HasColumnType("text")
                        .HasColumnName("objectives");

                    b.Property<string>("Skills")
                        .HasColumnType("text")
                        .HasColumnName("skills");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeCours")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_cours");

                    b.Property<int>("VolumeHours")
                        .HasColumnType("integer")
                        .HasColumnName("volume_hours");

                    b.HasKey("IdCours");

                    b.HasIndex("IdAffectation");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdGroupe");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdProfesseur");

                    b.HasIndex("IdSalle");

                    b.HasIndex("IdSemestre");

                    b.ToTable("cours", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Creneau", b =>
                {
                    b.Property<int>("IdCreneau")
                        .HasColumnType("integer")
                        .HasColumnName("id_creneau");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin");

                    b.Property<int>("IdCours")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours");

                    b.Property<string>("JourSemaine")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("jour_semaine");

                    b.Property<string>("SemaineType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("bpchar")
                        .HasColumnName("semaine_type");

                    b.HasKey("IdCreneau");

                    b.HasIndex("IdCours");

                    b.ToTable("creneau", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DemandeEdt", b =>
                {
                    b.Property<int>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_demande");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDemande"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateSouhaitee")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_souhaitee");

                    b.Property<TimeSpan?>("HeureDebutSouhaitee")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut_souhaitee");

                    b.Property<TimeSpan?>("HeureFinSouhaitee")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin_souhaitee");

                    b.Property<bool>("HorsDisponibilite")
                        .HasColumnType("boolean")
                        .HasColumnName("hors_disponibilite");

                    b.Property<int?>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int?>("IdCours")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours");

                    b.Property<int>("IdDemandeur")
                        .HasColumnType("integer")
                        .HasColumnName("id_demandeur");

                    b.Property<int?>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int?>("IdNiveau")
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau");

                    b.Property<int?>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<int?>("IdValidateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_validateur");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeDemande")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("type_demande");

                    b.HasKey("IdDemande");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdCours");

                    b.HasIndex("IdDemandeur");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdNiveau");

                    b.HasIndex("IdSalle");

                    b.HasIndex("IdValidateur");

                    b.ToTable("demande_edt", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DisponibiliteProf", b =>
                {
                    b.Property<int>("IdDispo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_dispo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDispo"));

                    b.Property<DateTime?>("DateSpecifique")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_specifique");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin");

                    b.Property<int?>("IdAnnee")
                        .HasColumnType("integer")
                        .HasColumnName("id_annee");

                    b.Property<int>("IdProfesseur")
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur");

                    b.Property<string>("JourSemaine")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("jour_semaine");

                    b.Property<string>("JourSemaineCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("jour_semaine_code");

                    b.Property<string>("SemaineType")
                        .HasMaxLength(1)
                        .HasColumnType("bpchar")
                        .HasColumnName("semaine_type");

                    b.Property<int>("TypeDisponibilite")
                        .HasColumnType("integer")
                        .HasColumnName("type_disponibilite");

                    b.HasKey("IdDispo");

                    b.HasIndex("IdAnnee");

                    b.HasIndex("IdProfesseur");

                    b.ToTable("disponibilite_prof", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Filiere", b =>
                {
                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer")
                        .HasColumnName("id_filiere");

                    b.Property<string>("CodeFiliere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_filiere");

                    b.Property<int>("IdMention")
                        .HasColumnType("integer")
                        .HasColumnName("id_mention");

                    b.Property<string>("NomFiliere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_filiere");

                    b.HasKey("IdFiliere");

                    b.HasIndex("IdMention");

                    b.ToTable("filiere", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClasseId")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.ToTable("groupes", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<string>("CodeMatiere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_matiere");

                    b.Property<int>("Credit")
                        .HasColumnType("integer")
                        .HasColumnName("credit");

                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer")
                        .HasColumnName("id_filiere");

                    b.Property<int?>("IdProfesseurResponsable")
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur_responsable");

                    b.Property<int>("IdRefSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_semestre");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_matiere");

                    b.Property<int>("VolumeHoraire")
                        .HasColumnType("integer")
                        .HasColumnName("volume_horaire");

                    b.HasKey("IdMatiere");

                    b.HasIndex("IdFiliere");

                    b.HasIndex("IdProfesseurResponsable");

                    b.HasIndex("IdRefSemestre");

                    b.ToTable("matiere", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Mention", b =>
                {
                    b.Property<int>("IdMention")
                        .HasColumnType("integer")
                        .HasColumnName("id_mention");

                    b.Property<string>("CodeMention")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_mention");

                    b.Property<string>("NomMention")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_mention");

                    b.HasKey("IdMention");

                    b.HasIndex("CodeMention")
                        .IsUnique();

                    b.ToTable("mention", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNiveau"));

                    b.Property<string>("CodeNiveau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code_niveau");

                    b.Property<int>("IdMention")
                        .HasColumnType("integer")
                        .HasColumnName("id_mention");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.HasKey("IdNiveau");

                    b.HasIndex("IdMention");

                    b.ToTable("niveau", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean");

                    b.Property<int>("IdProfesseur")
                        .HasColumnType("integer");

                    b.Property<string>("Lien")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdProfesseur");

                    b.ToTable("Notifications", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Prerequisite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_prerequisite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatiereId")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int>("PrerequisiteMatiereId")
                        .HasColumnType("integer")
                        .HasColumnName("id_prerequisite_matiere");

                    b.HasKey("Id");

                    b.HasIndex("MatiereId");

                    b.HasIndex("PrerequisiteMatiereId");

                    b.ToTable("prerequisites", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Professeur", b =>
                {
                    b.Property<int>("IdProfesseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProfesseur"));

                    b.Property<string>("Biographie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biographie");

                    b.Property<int>("CapaciteHoraireMax")
                        .HasColumnType("integer")
                        .HasColumnName("capacite_horaire_max");

                    b.Property<string>("CvUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cv_url");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateEmbauche")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_embauche");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modification");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean")
                        .HasColumnName("est_actif");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<int>("HeuresEffectuees")
                        .HasColumnType("integer")
                        .HasColumnName("heures_effectuees");

                    b.Property<int?>("IdAnneeAcademique")
                        .HasColumnType("integer")
                        .HasColumnName("id_annee_academique");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricule");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenom");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialite");

                    b.Property<string>("SpecialitesSecondaires")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("specialites_secondaires");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.Property<string>("TelephonePortable")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone_portable");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("titre");

                    b.HasKey("IdProfesseur");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdAnneeAcademique");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("professeur", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.PropositionAdmin", b =>
                {
                    b.Property<int>("IdProposition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_proposition");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProposition"));

                    b.Property<DateTime>("DateProposee")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_proposee");

                    b.Property<bool?>("EstAcceptee")
                        .HasColumnType("boolean")
                        .HasColumnName("est_acceptee");

                    b.Property<TimeSpan>("HeureDebutProposee")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut_proposee");

                    b.Property<TimeSpan>("HeureFinProposee")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin_proposee");

                    b.Property<int>("IdDemande")
                        .HasColumnType("integer")
                        .HasColumnName("id_demande");

                    b.Property<int>("IdSalleProposee")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle_proposee");

                    b.HasKey("IdProposition");

                    b.HasIndex("IdDemande");

                    b.HasIndex("IdSalleProposee");

                    b.ToTable("proposition_admin", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.RefSemestre", b =>
                {
                    b.Property<int>("IdRefSemestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_semestre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRefSemestre"));

                    b.Property<string>("CodeSemestre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code_semestre");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.HasKey("IdRefSemestre");

                    b.HasIndex("IdNiveau");

                    b.ToTable("ref_semestre", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.ReglageDisponibilite", b =>
                {
                    b.Property<int>("IdReglage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reglage");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReglage"));

                    b.Property<bool>("DimancheAutorise")
                        .HasColumnType("boolean")
                        .HasColumnName("dimanche_autorise");

                    b.Property<int>("DureeMinCreneauMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duree_min_creneau_minutes");

                    b.Property<TimeSpan>("HeureFermeture")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fermeture");

                    b.Property<TimeSpan>("HeureOuverture")
                        .HasColumnType("interval")
                        .HasColumnName("heure_ouverture");

                    b.Property<int>("IdAnnee")
                        .HasColumnType("integer")
                        .HasColumnName("id_annee");

                    b.Property<bool>("SamediAutorise")
                        .HasColumnType("boolean")
                        .HasColumnName("samedi_autorise");

                    b.HasKey("IdReglage");

                    b.HasIndex("IdAnnee");

                    b.ToTable("reglage_disponibilite", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<int>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("capacite");

                    b.Property<string>("CodeBatiment")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("bpchar")
                        .HasColumnName("code_batiment");

                    b.Property<int>("Etage")
                        .HasColumnType("integer")
                        .HasColumnName("etage");

                    b.Property<string>("NomSalle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_salle");

                    b.Property<string>("NumeroPorte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_porte");

                    b.Property<string>("TypeSalle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type_salle");

                    b.HasKey("IdSalle");

                    b.ToTable("salle", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_schedule");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin");

                    b.Property<int?>("ProfesseurId")
                        .HasColumnType("integer")
                        .HasColumnName("id_professeur");

                    b.Property<int?>("SalleId")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("session_type");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("id_subject");

                    b.HasKey("Id");

                    b.HasIndex("ProfesseurId");

                    b.HasIndex("SalleId");

                    b.HasIndex("SubjectId");

                    b.ToTable("schedules", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Seance", b =>
                {
                    b.Property<int>("IdSeance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_seance");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeance"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<int?>("GroupeId")
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe");

                    b.Property<int>("IdCours")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours");

                    b.Property<int?>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut");

                    b.HasKey("IdSeance");

                    b.HasIndex("CourseId");

                    b.HasIndex("IdSalle");

                    b.ToTable("seances", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Semestre", b =>
                {
                    b.Property<int>("IdSemestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSemestre"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<bool>("EstArchivee")
                        .HasColumnType("boolean")
                        .HasColumnName("est_archivee");

                    b.Property<int>("IdAnnee")
                        .HasColumnType("integer")
                        .HasColumnName("id_annee");

                    b.Property<int>("IdRefSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_semestre");

                    b.HasKey("IdSemestre");

                    b.HasIndex("IdAnnee");

                    b.HasIndex("IdRefSemestre");

                    b.ToTable("semestre", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_subject");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<int?>("FiliereId")
                        .HasColumnType("integer")
                        .HasColumnName("id_filiere");

                    b.Property<int>("Hours")
                        .HasColumnType("integer")
                        .HasColumnName("hours");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int?>("MentionId")
                        .HasColumnType("integer")
                        .HasColumnName("id_mention");

                    b.Property<int?>("NiveauId")
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau");

                    b.Property<int?>("SemestreId")
                        .HasColumnType("integer")
                        .HasColumnName("id_semestre");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FiliereId");

                    b.HasIndex("MentionId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("SemestreId");

                    b.ToTable("subjects", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateDerniereConnexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_derniere_connexion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PremierLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("premier_login");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("StatutCompte")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("statut_compte");

                    b.Property<string>("TokenActivation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_activation");

                    b.Property<DateTime?>("TokenExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expiration");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utilisateur", "public");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.AffectationMatiere", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Classe", "Classe")
                        .WithMany("AffectationsMatieres")
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Matiere", "Matiere")
                        .WithMany("AffectationsMatieres")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Professeur", "Professeur")
                        .WithMany("AffectationsMatieres")
                        .HasForeignKey("IdProfesseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Semestre", "Semestre")
                        .WithMany("AffectationsMatieres")
                        .HasForeignKey("IdSemestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Matiere");

                    b.Navigation("Professeur");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Classe", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.AnneeAcademique", "AnneeAcademique")
                        .WithMany("Classes")
                        .HasForeignKey("IdAnneeAcademique")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Filiere", "Filiere")
                        .WithMany("Classes")
                        .HasForeignKey("IdFiliere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Niveau", "Niveau")
                        .WithMany()
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeAcademique");

                    b.Navigation("Filiere");

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Cours", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.AffectationMatiere", "AffectationMatiere")
                        .WithMany("Cours")
                        .HasForeignKey("IdAffectation");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Classe", "Classe")
                        .WithMany("Cours")
                        .HasForeignKey("IdClasse");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("IdGroupe");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Matiere", "Matiere")
                        .WithMany("Cours")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Professeur", "Professeur")
                        .WithMany("Cours")
                        .HasForeignKey("IdProfesseur");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Salle", "Salle")
                        .WithMany("Cours")
                        .HasForeignKey("IdSalle");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Semestre", "Semestre")
                        .WithMany("Cours")
                        .HasForeignKey("IdSemestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffectationMatiere");

                    b.Navigation("Classe");

                    b.Navigation("Groupe");

                    b.Navigation("Matiere");

                    b.Navigation("Professeur");

                    b.Navigation("Salle");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Creneau", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Cours", "Cours")
                        .WithMany("Creneaux")
                        .HasForeignKey("IdCours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DemandeEdt", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("IdClasse");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Cours", "Cours")
                        .WithMany("DemandesEdt")
                        .HasForeignKey("IdCours");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Utilisateur", "Demandeur")
                        .WithMany()
                        .HasForeignKey("IdDemandeur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("IdMatiere");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Niveau", "Niveau")
                        .WithMany()
                        .HasForeignKey("IdNiveau");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Salle", "Salle")
                        .WithMany("DemandesEdt")
                        .HasForeignKey("IdSalle");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Utilisateur", "Validateur")
                        .WithMany()
                        .HasForeignKey("IdValidateur");

                    b.Navigation("Classe");

                    b.Navigation("Cours");

                    b.Navigation("Demandeur");

                    b.Navigation("Matiere");

                    b.Navigation("Niveau");

                    b.Navigation("Salle");

                    b.Navigation("Validateur");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DisponibiliteProf", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.AnneeAcademique", "AnneeAcademique")
                        .WithMany()
                        .HasForeignKey("IdAnnee");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Professeur", "Professeur")
                        .WithMany("Disponibilites")
                        .HasForeignKey("IdProfesseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeAcademique");

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Filiere", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Mention", "Mention")
                        .WithMany("Filieres")
                        .HasForeignKey("IdMention")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mention");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Groupe", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Matiere", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Filiere", "Filiere")
                        .WithMany("Matieres")
                        .HasForeignKey("IdFiliere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Professeur", "ProfesseurResponsable")
                        .WithMany("MatieresResponsable")
                        .HasForeignKey("IdProfesseurResponsable");

                    b.HasOne("Gestion_SalleClasseEDT.Models.RefSemestre", "RefSemestre")
                        .WithMany("Matieres")
                        .HasForeignKey("IdRefSemestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");

                    b.Navigation("ProfesseurResponsable");

                    b.Navigation("RefSemestre");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Niveau", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Mention", "Mention")
                        .WithMany("Niveaux")
                        .HasForeignKey("IdMention")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mention");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Notification", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Professeur", "Professeur")
                        .WithMany()
                        .HasForeignKey("IdProfesseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Prerequisite", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Matiere", "Matiere")
                        .WithMany("Prerequisites")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Matiere", "PrerequisiteMatiere")
                        .WithMany("IsPrerequisiteFor")
                        .HasForeignKey("PrerequisiteMatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("PrerequisiteMatiere");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Professeur", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.AnneeAcademique", "AnneeAcademique")
                        .WithMany("Professeurs")
                        .HasForeignKey("IdAnneeAcademique");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Utilisateur", "Utilisateur")
                        .WithOne("Professeur")
                        .HasForeignKey("Gestion_SalleClasseEDT.Models.Professeur", "IdUtilisateur");

                    b.Navigation("AnneeAcademique");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.PropositionAdmin", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.DemandeEdt", "Demande")
                        .WithMany("Propositions")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("IdSalleProposee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.RefSemestre", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Niveau", "Niveau")
                        .WithMany("RefSemestres")
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.ReglageDisponibilite", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.AnneeAcademique", "AnneeAcademique")
                        .WithMany()
                        .HasForeignKey("IdAnnee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeAcademique");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Schedule", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Professeur", "Professeur")
                        .WithMany()
                        .HasForeignKey("ProfesseurId");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("SalleId");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.Navigation("Professeur");

                    b.Navigation("Salle");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Seance", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Cours", "Cours")
                        .WithMany("Seances")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("IdSalle");

                    b.Navigation("Cours");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Semestre", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.AnneeAcademique", "AnneeAcademique")
                        .WithMany("Semestres")
                        .HasForeignKey("IdAnnee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_SalleClasseEDT.Models.RefSemestre", "RefSemestre")
                        .WithMany("Semestres")
                        .HasForeignKey("IdRefSemestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeAcademique");

                    b.Navigation("RefSemestre");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Subject", b =>
                {
                    b.HasOne("Gestion_SalleClasseEDT.Models.Filiere", "Filiere")
                        .WithMany()
                        .HasForeignKey("FiliereId");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Mention", "Mention")
                        .WithMany()
                        .HasForeignKey("MentionId");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Niveau", "Niveau")
                        .WithMany()
                        .HasForeignKey("NiveauId");

                    b.HasOne("Gestion_SalleClasseEDT.Models.Semestre", "Semestre")
                        .WithMany()
                        .HasForeignKey("SemestreId");

                    b.Navigation("Filiere");

                    b.Navigation("Mention");

                    b.Navigation("Niveau");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.AffectationMatiere", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.AnneeAcademique", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Professeurs");

                    b.Navigation("Semestres");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Classe", b =>
                {
                    b.Navigation("AffectationsMatieres");

                    b.Navigation("Cours");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Cours", b =>
                {
                    b.Navigation("Creneaux");

                    b.Navigation("DemandesEdt");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.DemandeEdt", b =>
                {
                    b.Navigation("Propositions");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Filiere", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Matieres");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Matiere", b =>
                {
                    b.Navigation("AffectationsMatieres");

                    b.Navigation("Cours");

                    b.Navigation("IsPrerequisiteFor");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Mention", b =>
                {
                    b.Navigation("Filieres");

                    b.Navigation("Niveaux");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Niveau", b =>
                {
                    b.Navigation("RefSemestres");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Professeur", b =>
                {
                    b.Navigation("AffectationsMatieres");

                    b.Navigation("Cours");

                    b.Navigation("Disponibilites");

                    b.Navigation("MatieresResponsable");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.RefSemestre", b =>
                {
                    b.Navigation("Matieres");

                    b.Navigation("Semestres");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Salle", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("DemandesEdt");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Semestre", b =>
                {
                    b.Navigation("AffectationsMatieres");

                    b.Navigation("Cours");
                });

            modelBuilder.Entity("Gestion_SalleClasseEDT.Models.Utilisateur", b =>
                {
                    b.Navigation("Professeur");
                });
#pragma warning restore 612, 618
        }
    }
}
